Repository borisbu/OctoRelay, pull requests merged in 2023-10, with the labels that each got.

#235 Upgrading UI dependencies
  ts/.eslintrc.json
  ts/bindings.spec.ts
  ts/helpers/countdown.spec.ts
  ts/helpers/countdown.ts
  ts/helpers/hints.ts
  ts/model/OctoRelayModel.spec.ts
  ts/model/OctoRelayModel.ts
  ts/package.json
  ts/types/OctoPrint.d.ts
  ts/types/OwnModel.ts
  ts/yarn.lock
Labels: dependencies

#234 API: The `update` command `target` parameter
  README.md
  octoprint_octorelay/__init__.py
  tests/test_init.py
Labels: enhancement

#238 Readme: Fix quoted illustrations
  README.md
  img/gpio.png
  img/relay.jpg
Labels: documentation

#237 🚀 3.12.0
  CHANGELOG.md
  README.md
  img/gpio.png
  img/relay.jpg
  octoprint_octorelay/__init__.py
  tests/test_init.py
  ts/.eslintrc.json
  ts/bindings.spec.ts
  ts/helpers/countdown.spec.ts
  ts/helpers/countdown.ts
  ts/helpers/hints.ts
  ts/model/OctoRelayModel.spec.ts
  ts/model/OctoRelayModel.ts
  ts/package.json
  ts/types/OctoPrint.d.ts
  ts/types/OwnModel.ts
  ts/yarn.lock
Labels: documentation, enhancement, coverage, refactoring, release, dependencies

#231 Generating CSS from SCSS.
  .gitignore
  MANIFEST.in
  octoprint_octorelay/static/css/.gitkeep
  octoprint_octorelay/static/css/octorelay.css
  ts/package.json
  ts/styles/navbar.scss
  ts/styles/octorelay.scss
  ts/styles/settings.scss
  ts/yarn.lock
Labels: refactoring, release, dependencies

#216 Using `mypy` for type constraints
  .github/workflows/CI.yaml
  mypy.ini
  octoprint_octorelay/__init__.py
  octoprint_octorelay/model.py
  setup.py
  tests/test_init.py
Labels: coverage, refactoring, dependencies

#240 Ref: API: Moving response shaping out of handlers
  octoprint_octorelay/__init__.py
  octoprint_octorelay/exceptions.py
  tests/test_init.py
Labels: enhancement, refactoring

#241 Ref: Moving required params checks
  octoprint_octorelay/__init__.py
  tests/test_init.py
Labels: refactoring

#242 Feat: API v2
  octoprint_octorelay/__init__.py
  octoprint_octorelay/listing.py
  setup.py
  tests/test_init.py
  ts/helpers/actions.spec.ts
  ts/helpers/actions.ts
Labels: enhancement, refactoring

#239 🚀 3.14.0
  .github/workflows/CI.yaml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  README.md
  mypy.ini
  octoprint_octorelay/__init__.py
  octoprint_octorelay/exceptions.py
  octoprint_octorelay/listing.py
  octoprint_octorelay/model.py
  octoprint_octorelay/static/css/.gitkeep
  octoprint_octorelay/static/css/octorelay.css
  setup.py
  tests/test_init.py
  ts/helpers/actions.spec.ts
  ts/helpers/actions.ts
  ts/package.json
  ts/styles/navbar.scss
  ts/styles/octorelay.scss
  ts/styles/settings.scss
  ts/yarn.lock
Labels: enhancement, coverage, refactoring, release, dependencies
