Repository borisbu/OctoRelay, pull requests merged in 2023-07, with the labels that each got.

#64 Creating the LICENSE file
  LICENSE
Labels: documentation

#69 Making Changelog, Updating Readme
  CHANGELOG.md
  README.md
Labels: documentation

#67 Making a pre-release channel configuration.
  octoprint_octorelay/__init__.py
Labels: enhancement

#70 Preparing v1.3.0 release
  CHANGELOG.md
  setup.py
Labels: documentation

#71 Releasing v1.3.0
  CHANGELOG.md
  LICENSE
  README.md
  octoprint_octorelay/__init__.py
  setup.py
Labels: release

#68 JS: Types constraints and tests
  .github/workflows/CI.yaml
  octoprint_octorelay/static/js/octorelay.js
  ts/.eslintrc.json
  ts/.gitignore
  ts/OctoPrint.d.ts
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/jest.config.json
  ts/octorelay.spec.ts
  ts/octorelay.ts
  ts/package.json
  ts/tsconfig.build.json
  ts/tsconfig.json
  ts/yarn.lock
Labels: enhancement, coverage, refactoring

#72 Moving JS from template
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  ts/OctoPrint.d.ts
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/octorelay.spec.ts
  ts/octorelay.ts
Labels: enhancement, coverage, refactoring

#55 Make `print_started()` only process "active" relay configs.
  octoprint_octorelay/__init__.py
Labels: bug

#77 Releasing `1.4.1`
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  setup.py
Labels: bug, documentation, release

#79 Fix `height` property of the icons in initial config
  octoprint_octorelay/__init__.py
Labels: bug

#81 Releasing 1.4.2
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  setup.py
Labels: bug, release

#75 Requiring Python 3.7
  CHANGELOG.md
  octoprint_octorelay/__init__.py
Labels: breaking, dependencies

#78 SVG icons
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/static/img/3d-printer.png
  octoprint_octorelay/static/img/3d-printer.svg
  octoprint_octorelay/static/img/fan-24.png
  octoprint_octorelay/static/img/fan.svg
  octoprint_octorelay/static/img/refresh.png
  octoprint_octorelay/static/img/webcam.png
  octoprint_octorelay/static/img/webcam.svg
Labels: enhancement, breaking

#80 JS: changing the target level to ES6.
  CHANGELOG.md
  octoprint_octorelay/static/js/octorelay.js
  ts/tsconfig.json
Labels: enhancement, breaking

#82 2.0: Fix `img` nodes shaking
  octoprint_octorelay/__init__.py
  octoprint_octorelay/static/img/3d-printer.svg
  octoprint_octorelay/static/img/fan.svg
  octoprint_octorelay/static/img/webcam.svg
Labels: bug

#83 🚀 Releasing 2.0.0
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/static/img/3d-printer.png
  octoprint_octorelay/static/img/3d-printer.svg
  octoprint_octorelay/static/img/fan-24.png
  octoprint_octorelay/static/img/fan.svg
  octoprint_octorelay/static/img/refresh.png
  octoprint_octorelay/static/img/webcam.png
  octoprint_octorelay/static/img/webcam.svg
  octoprint_octorelay/static/js/octorelay.js
  setup.py
  ts/tsconfig.json
Labels: enhancement, release, breaking, dependencies

#84 Fix incorrect description of the OS command setting.
  README.md
Labels: documentation

#85 CI job and basic Python tests
  .github/workflows/CI.yaml
  octoprint_octorelay/test__init.py
Labels: coverage

#86 Complete Python tests
  .github/workflows/CI.yaml
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
Labels: coverage

#48 Fixes for non-inverted relay
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
Labels: bug

#88 Releasing 2.0.1
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
  setup.py
Labels: bug, documentation, coverage, release

#89 Improving and refactoring the tests
  .github/workflows/CI.yaml
  octoprint_octorelay/test__init.py
Labels: coverage, refactoring

#90 CI: ensure testing against OctoPrint 1.8
  .github/workflows/CI.yaml
Labels: coverage

#91 Readme: Add CI badge
  README.md
Labels: documentation

#92 Coveralls integration
  .github/workflows/CI.yaml
  README.md
Labels: documentation, coverage

#93 Merging develop
  .github/workflows/CI.yaml
  README.md
  octoprint_octorelay/test__init.py
Labels: documentation, coverage, refactoring

#97 Listing the required API param `pin`.
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
Labels: bug

#98 Releasing 2.0.2
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
  setup.py
Labels: bug, release

#99 Prohibit operating relays for readonly users
  CHANGELOG.md
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  octoprint_octorelay/test__init.py
Labels: bug, documentation, enhancement

#100 Relay switching permission
  CHANGELOG.md
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  octoprint_octorelay/test__init.py
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/octorelay.spec.ts
  ts/octorelay.ts
Labels: bug, documentation, enhancement

#101 Releasing 2.1.0
  CHANGELOG.md
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  octoprint_octorelay/test__init.py
  setup.py
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/octorelay.spec.ts
  ts/octorelay.ts
Labels: bug, documentation, enhancement, release

#44 `@OCTORELAY` command support
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
Labels: enhancement

#105 Releasing 2.2.0
  CHANGELOG.md
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
  setup.py
Labels: enhancement, release

#108 Add missing future params to `get_additional_permissions`
  .gitignore
  octoprint_octorelay/__init__.py
Labels: refactoring

#109 Naming: relay state instead of LED one
  octoprint_octorelay/__init__.py
Labels: refactoring

#110 Releasing 2.2.1
  .gitignore
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  setup.py
Labels: refactoring, release

#111 Ref: replacing `dict()` with curly braces.
  octoprint_octorelay/__init__.py
Labels: refactoring

#112 Ref: extracting constants
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
Labels: refactoring

#117 Ref: extracting constants
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
Labels: refactoring

#118 Releasing 2.2.2
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
  setup.py
Labels: refactoring, release

#119 Using f-strings instead of `.format()`
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
Labels: refactoring

#121 CodeQL check
  .github/workflows/codeql.yml
Labels: coverage

#120 Ensure booleans: initialisations and strict comparison
  octoprint_octorelay/__init__.py
  octoprint_octorelay/test__init.py
Labels: coverage, refactoring

#123 Releasing 2.2.3
  .github/workflows/codeql.yml
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
  setup.py
Labels: refactoring, release

#124 Readme: add CodeQL badge
  README.md
Labels: documentation

#125 UI: Fix hover state
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/octorelay.spec.ts
  ts/octorelay.ts
  ts/yarn.lock
Labels: bug

#126 Releasing 2.2.4
  CHANGELOG.md
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/templates/octorelay_navbar.jinja2
  setup.py
  ts/__snapshots__/octorelay.spec.ts.snap
  ts/octorelay.spec.ts
  ts/octorelay.ts
  ts/yarn.lock
Labels: bug, release

#127 Readme: new controls image.
  README.md
  img/controls.jpg
  img/screenshot.png
Labels: documentation

#128 Readme: shorter introduction, neater appearance.
  README.md
Labels: documentation

#129 Distributable ZIP-package
  .gitattributes
  .github/workflows/CI.yaml
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/_static_version.py
  octoprint_octorelay/_version.py
  octoprint_octorelay/const.py
  octoprint_octorelay/static/js/.gitkeep
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/test__init.py
  setup.py
Labels: documentation, enhancement, release

#131 Hotfix: Reverting a const for templates.
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  setup.py
Labels: bug, release

#132 JS: notification stub in sources
  .github/workflows/release.yaml
  CHANGELOG.md
  octoprint_octorelay/static/js/.gitkeep
  octoprint_octorelay/static/js/octorelay.js
  ts/package.json
  ts/stub/octorelay.ts
  ts/tsconfig.build.json
  ts/tsconfig.stub.json
Labels: documentation, enhancement, release, breaking

#133 🚀 Releasing 3.0.0
  .gitattributes
  .github/workflows/CI.yaml
  .github/workflows/release.yaml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  README.md
  octoprint_octorelay/__init__.py
  octoprint_octorelay/_static_version.py
  octoprint_octorelay/_version.py
  octoprint_octorelay/const.py
  octoprint_octorelay/static/js/octorelay.js
  octoprint_octorelay/test__init.py
  setup.py
  ts/package.json
  ts/stub/octorelay.ts
  ts/tsconfig.build.json
  ts/tsconfig.stub.json
Labels: documentation, refactoring, release, breaking

#134 Testing actual compatibility
  .github/workflows/CI.yaml
  .github/workflows/release.yaml
Labels: documentation, coverage, release

#116 `pylint`: Enforcing code style
  .github/workflows/CI.yaml
  .gitignore
  .pylintrc
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
Labels: coverage, refactoring

#136 Revert: const for default settings.
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
Labels: bug

#137 Immutable: Replacing const with getters
  octoprint_octorelay/__init__.py
  octoprint_octorelay/const.py
  octoprint_octorelay/test__init.py
Labels: coverage, refactoring
