Repository borisbu/OctoRelay, pull requests merged in 2024-07, with the labels that each got.

#275 Upgrading UI dependencies
  ui/eslint.config.js
  ui/mocks/jQuery.ts
  ui/model/messageHandler.spec.ts
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#276 Using Vitest 2.0
  ui/helpers/countdown.spec.ts
  ui/package.json
  ui/vitest.config.ts
  ui/yarn.lock
Labels: coverage, dependencies

#277 Upgrading `prettier`
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#278 Use HappyDOM
  ui/bindings.spec.ts
  ui/package.json
  ui/vitest.config.ts
  ui/yarn.lock
Labels: refactoring, dependencies

#279 Fix `self` to `this` alias in model
  ui/model/OctoRelayModel.ts
Labels: refactoring

#269 🚀 4.2.1
  CHANGELOG.md
  ui/.eslintrc.json
  ui/bindings.spec.ts
  ui/eslint.config.js
  ui/helpers/countdown.spec.ts
  ui/helpers/hints.ts
  ui/mocks/jQuery.ts
  ui/model/OctoRelayModel.ts
  ui/model/messageHandler.spec.ts
  ui/package.json
  ui/types/Hints.ts
  ui/types/OctoPrint.d.ts
  ui/vitest.config.ts
  ui/yarn.lock
Labels: coverage, refactoring, release, dependencies

#274 Migration to gpiozero
  .github/workflows/CI.yaml
  .github/workflows/release.yaml
  .pylintrc
  README.md
  mypy.ini
  octoprint_octorelay/__init__.py
  octoprint_octorelay/driver.py
  setup.py
  tests/test_driver.py
  tests/test_init.py
Labels: enhancement, breaking, dependencies

#281 fix driver for automatic pin factory
  octoprint_octorelay/driver.py
  setup.py
Labels: refactoring

#215 Remove `typing-extensions`
  octoprint_octorelay/listing.py
  octoprint_octorelay/model.py
  setup.py
Labels: dependencies

#282 Restore standalone `xor`
  octoprint_octorelay/driver.py
Labels: refactoring

#283 Ref: naming entities in the driver
  octoprint_octorelay/__init__.py
  octoprint_octorelay/driver.py
  tests/test_driver.py
  tests/test_init.py
Labels: refactoring

#280 🚀 5.0.0
  .github/workflows/CI.yaml
  .github/workflows/release.yaml
  .pylintrc
  CHANGELOG.md
  README.md
  mypy.ini
  octoprint_octorelay/__init__.py
  octoprint_octorelay/driver.py
  octoprint_octorelay/listing.py
  octoprint_octorelay/model.py
  setup.py
  tests/test_driver.py
  tests/test_init.py
Labels: documentation, enhancement, refactoring, release, breaking, dependencies

#290 Upgrading ESLing and Co
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#291 Upgrading all dependencies.
  ui/yarn.lock
Labels: dependencies

#289 🚀 5.0.1
  CHANGELOG.md
  octoprint_octorelay/__init__.py
  setup.py
  ui/package.json
  ui/yarn.lock
Labels: refactoring, release, dependencies

#294 Better way to override eslint import plugin.
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#296 Upgrading typescript-eslint
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#297 Using stable `typescript-eslint` v8
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#298 UI: Upgrading all dependencies
  ui/package.json
  ui/yarn.lock
Labels: dependencies
